# == WARNING === WARNING === WARNING === WARNING === WARNING === WARNING === WARNING === WARNING === WARNING ===
# EVERYTHING HERE IS SET TO TEST LOCALLY, DO NOT SHARE THIS FILE IN THE REMOTE IF YOU WANT TO PUT IT IN PRODUCTION!!!
# == WARNING === WARNING === WARNING === WARNING === WARNING === WARNING === WARNING === WARNING === WARNING ===
# == WARNING === WARNING === WARNING === WARNING === WARNING === WARNING === WARNING === WARNING === WARNING ===
# EVERYTHING HERE IS SET TO TEST LOCALLY, DO NOT SHARE THIS FILE IN THE REMOTE IF YOU WANT TO PUT IT IN PRODUCTION!!!
# == WARNING === WARNING === WARNING === WARNING === WARNING === WARNING === WARNING === WARNING === WARNING ===

spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/ctruco}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:postgres}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:password}
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQL9Dialect
spring.data.mongodb.uri=${SPRING_DATA_MONGODB_URI:mongodb://rootuser:rootpass@localhost:27017/ctruco?authSource=admin}
spring.data.mongodb.uuid-representation=standard
application.jwt.secretKey=Apesar de você Amanhã há de ser Outro dia Eu pergunto a você Onde vai se esconder Da enorme euforia Como vai proibir Quando o galo insistir Em cantar Água nova brotando E a gente se amando
application.jwt.tokenPrefix=Bearer 
application.jwt.tokenExpirationAfterMinutes=3
application.jwt.refreshTokenExpirationAfterDays=14
